---
galaxy_info:
  author: Hardik Modi
  description: Simple NGINX role for Ubuntu
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []

